#!/bin/bash

# Auto-Build Environment Setup for Is BVG Fucked Up?
# Generated by Planner Agent
#
# This script sets up the development environment for the static website.
# No external services needed - just a simple HTTP server.

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if Python is available for serving
if ! command -v python3 &> /dev/null; then
    if ! command -v python &> /dev/null; then
        echo -e "${RED}Error: Python 3 or Python is required but not installed.${NC}"
        exit 1
    fi
    PYTHON_CMD="python"
else
    PYTHON_CMD="python3"
fi

echo -e "${BLUE}Environment:${NC}"
echo "  Project: Is BVG Fucked Up?"
echo "  Type: Static Website (HTML/CSS/JavaScript)"
echo "  Stack: Vanilla ES5 JavaScript"
echo "  Data Source: VBB Transport REST API v6"
echo ""

# Check Node.js/npm availability
if command -v npm &> /dev/null; then
    echo -e "${BLUE}Node.js/npm detected:${NC}"
    npm_version=$(npm --version)
    echo "  npm version: $npm_version"
    echo ""
fi

# Starting the HTTP server
echo -e "${YELLOW}Starting HTTP server on port 8000...${NC}"
echo "  Command: $PYTHON_CMD -m http.server 8000"
echo ""

cd "$(dirname "$0")"

# Start the server
$PYTHON_CMD -m http.server 8000 &
SERVER_PID=$!

# Wait for server to start
sleep 1

if ! kill -0 $SERVER_PID 2>/dev/null; then
    echo -e "${RED}Failed to start server${NC}"
    exit 1
fi

echo ""
echo "========================================"
echo -e "${GREEN}Development Environment Ready!${NC}"
echo "========================================"
echo ""
echo -e "${BLUE}Access Points:${NC}"
echo "  Website:  ${GREEN}http://localhost:8000${NC}"
echo "  Files:    $(pwd)"
echo ""

echo -e "${BLUE}Files Structure:${NC}"
echo "  index.html           - Main page"
echo "  js/app.js            - Application logic"
echo "  css/style.css        - Styling"
echo ""

echo -e "${BLUE}Development Notes:${NC}"
echo "  - Data refreshes every 60 seconds"
echo "  - Monitors 4 Berlin transit stations"
echo "  - No authentication required (public API)"
echo "  - Open browser console (F12) to debug"
echo ""

echo -e "${YELLOW}Press Ctrl+C to stop the server${NC}"
echo ""

# Keep the script running
wait $SERVER_PID
